import { requireAdminApi } from "../../../../lib/admin-auth";
import { publicAssetPaths, sourceBundleBase64 } from "../../../../lib/source-bundle.generated";
import { strToU8, unzipSync, zipSync } from "fflate";

export async function GET(request:Request) {
  if (!(await requireAdminApi())) return Response.json({ error: "Unauthorized" }, { status: 401 });
  try{
    const files=unzipSync(Uint8Array.from(atob(sourceBundleBase64),c=>c.charCodeAt(0)));
    const { env } = await import("cloudflare:workers");
    const origin=new URL(request.url).origin;
    for(const path of publicAssetPaths){
      const url=`${origin}/${path}`;
      const response=(env as any).ASSETS
        ?await (env as any).ASSETS.fetch(new Request(url))
        :await fetch(url);
      if(!response.ok)throw new Error(`Could not include built-in asset: ${path}`);
      files[`public/${path}`]=new Uint8Array(await response.arrayBuffer());
    }
    await env.DB.prepare("CREATE TABLE IF NOT EXISTS site_settings (id INTEGER PRIMARY KEY, data TEXT NOT NULL DEFAULT '{}', updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)").run();
    const row=await env.DB.prepare("SELECT data FROM site_settings WHERE id = 1").first<{data:string}>();
    const currentSettings=row?.data?JSON.parse(row.data):{};
    files["handover/current-site-settings.json"]=strToU8(JSON.stringify(currentSettings,null,2));
    files["lib/local-settings.generated.ts"]=strToU8(`// Generated by the complete website export.\nexport const localExportSettings:Record<string,any>=${JSON.stringify(currentSettings,null,2)};\n`);
    files["handover/README-FIRST.txt"]=strToU8(
`SHIVA KRUPA POLYCLINIC — COMPLETE WEBSITE HANDOVER

This package contains the editable Next.js, React and TypeScript source code, built-in website assets, current admin settings and uploaded media.

LOCAL SETUP
1. Install Node.js 22 or later.
2. Run: npm install
3. Run: npm run dev
4. Open the local address printed in the terminal.

DEPLOYMENT
The current production build uses Cloudflare Workers, D1 and R2. Create equivalent DB and BUCKET bindings when moving it to another Cloudflare account. The database-ready settings backup is in handover/current-site-settings.json and uploaded media is under handover/uploads/.

Never commit real passwords, API keys or production secrets to source control.
`);
    let cursor: string|undefined;
    do{
      const listed=await env.BUCKET.list({cursor});
      for(const item of listed.objects){
        const object=await env.BUCKET.get(item.key);
        if(object){
          const bytes=new Uint8Array(await object.arrayBuffer());
          files[`handover/uploads/${item.key}`]=bytes;
          files[`public/media/${item.key}`]=bytes;
        }
      }
      cursor=listed.truncated?listed.cursor:undefined;
    }while(cursor);
    const archive=zipSync(files,{level:4});
    return new Response(archive,{headers:{
      "content-type":"application/zip",
      "content-length":String(archive.byteLength),
      "content-disposition":`attachment; filename="shiva-krupa-complete-website.zip"`,
      "cache-control":"no-store",
    }});
  }catch(error){
    return Response.json({error:error instanceof Error?error.message:"The complete website package could not be prepared."},{status:500});
  }
}
