"use client";
import { FormEvent, useEffect, useState } from "react";
type User={email:string;role:"viewer"|"admin";created_at:string};
export default function AccessManager(){
 const [users,setUsers]=useState<User[]>([]),[status,setStatus]=useState("");
 async function load(){const r=await fetch("/api/admin/access-users",{cache:"no-store"});const j=await r.json();if(r.ok)setUsers(j.users||[]);else setStatus(j.error||"Could not load access list.")}
 useEffect(()=>{load()},[]);
 async function add(e:FormEvent<HTMLFormElement>){e.preventDefault();setStatus("Adding access…");const f=new FormData(e.currentTarget),r=await fetch("/api/admin/access-users",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email:f.get("email"),role:f.get("role"),password:f.get("password")})}),j=await r.json();if(!r.ok){setStatus(j.error||"Could not add access.");return}e.currentTarget.reset();setStatus("Access added. Share the email and temporary password securely.");await load()}
 async function remove(email:string){if(!confirm(`Remove access for ${email}?`))return;await fetch("/api/admin/access-users",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({email})});setStatus("Access removed and active sessions revoked.");await load()}
 return <section className="admin-card" id="access"><h3>Website and admin access</h3><p>Add any personal or office email. Viewers can access a private website; administrators can also open the Content Studio. Passwords are encrypted and are never shown again.</p><form className="access-add" onSubmit={add}><label>Email address<input name="email" type="email" required placeholder="name@example.com"/></label><label>Access level<select name="role"><option value="viewer">Website viewer</option><option value="admin">Website + admin panel</option></select></label><label>Temporary password<input name="password" type="password" required minLength={8} placeholder="Minimum 8 characters"/></label><button type="submit">Add or update access</button></form>{status&&<p className="admin-status">{status}</p>}<div className="access-list">{users.length?users.map(u=><div key={u.email}><span><b>{u.email}</b><small>{u.role==="admin"?"Website + admin panel":"Website only"}</small></span><button type="button" onClick={()=>remove(u.email)}>Remove</button></div>):<p>No additional users have been added.</p>}</div></section>
}
