import { servicePages } from "./site-content";

export const defaultSettings = {
  clinicName:"Shiva Krupa Polyclinic & Laboratory",
  strapline:"Women’s Health, Fertility & Family Medicine",
  phone:"080 2348 9363", phoneHref:"08023489363", whatsapp:"919187392697",
  email:"draishwarya02@gmail.com", address:"1st Floor, 131/3, 80 Feet Ring Road, KHB Colony, Basaveshwar Nagar, Bengaluru 560079",
  hours:"Monday–Saturday · 10:00 AM–7:00 PM",
  appointmentDelivery:"whatsapp",
  googleBookingEnabled:false,
  googleBookingUrls:{
    aishwarya:"",
    nagarajaiah:"",
  },
  consultationSlots:[
    {doctor:"Dr Aishwarya V Mathikatti",label:"Morning",time:"10:00 AM–1:00 PM"},
    {doctor:"Dr Aishwarya V Mathikatti",label:"Evening",time:"5:00 PM–7:00 PM"},
    {doctor:"Dr L. P. Nagarajaiah",label:"Morning",time:"9:00 AM–12:00 PM"},
    {doctor:"Dr L. P. Nagarajaiah",label:"Evening",time:"5:00 PM–7:00 PM"},
  ],
  calculatorMoveVersion:1,
  consultationSlotsVersion:1,
  primary:"#b54f76", accent:"#c79660", background:"#fff8fb",
  ink:"#402532", muted:"#77636c", surface:"#ffffff", soft:"#fdf0f5", deep:"#702a47", themeMode:"light",
  headingFont:"Cormorant Garamond", bodyFont:"Inter", radius:"12",
  contentWidth:"wide", cardStyle:"soft", buttonStyle:"rounded", animationStyle:"soft",
  headerStyle:"classic", heroLayout:"split",
  heroTitle:"Care that listens. Expertise that stays with you.",
  heroSubtitle:"Specialist women’s healthcare led by Dr Aishwarya V Mathikatti, supported by two generations of trusted medical experience.",
  heroImage:"",
  homeHeroTitleSize:66, homeHeroSubtitleSize:18, homeHeroTextWidth:54, homeHeroImageX:68, homeHeroImageY:35, homeHeroOverlay:64, homeHeroSizeVersion:1,
  homeIntroHeadingSize:58, homeIntroBodySize:14,
  homeServicesHeadingSize:58, homeServiceCardTitleSize:27, homeServiceCardBodySize:12,
  homeAwardsHeadingSize:58, homeAwardsBodySize:13,
  homeInsightsHeadingSize:58, homeBlogCardTitleSize:28, homeBlogCardBodySize:12, showBlogImagesHome:false,
  homeBlogImagePreferenceVersion:1,
  announcement:"Consultations in Basaveshwar Nagar",
  showAnnouncementBar:false,
  aboutHeroHeight:420,
  faqExpansionVersion:1,
  serviceDetailsVersion:3,
  conditionsVersion:1,
  conditions:[
    "PCOS/PCOD",
    "Vaginal Tightening",
    "Menopause Care",
    "High-risk Pregnancy",
    "Infertility Evaluation",
    "Male Infertility",
  ],
  specializationImages:{
    gynaecology:"/specializations/gynaecology.webp",
    "pregnancy-care":"/specializations/pregnancy-care.webp",
    "fertility-ivf":"/specializations/fertility-ivf.webp",
    procedures:"/specializations/procedures.webp",
    "general-medicine":"/specializations/general-medicine.webp",
  },
  homeSectionOrder:["intro","services","conditions","awards","insights"],
  showIntro:true, showServices:true, showConditions:true, showAwards:true, showTestimonials:true, showInsights:true,
  showPhotos:true, showVideos:true, websitePrivate:false,
  servicesLayout:"grid",
  calculatorPlacement:"blogs",
  appointmentPlacement:"contact",
  showFloatingCall:true, showFloatingWhatsapp:true,
  navDoctors:true, navSpecialities:true, navResources:true, navContact:true,
  blogNavLabel:"Blogs", blogPageLabel:"HEALTH INSIGHTS", blogPageTitle:"Clear medical guidance for better decisions.",
  pages:servicePages,
  blogs:[
    {slug:"pcos-can-it-be-cured",category:"PCOS & Hormonal Health",title:"Can PCOS Be Cured? Understanding What Treatment Can Really Achieve",heroShort:"PCOS can be managed very effectively, but there is no single permanent cure. The right plan depends on your symptoms, health risks and fertility goals.",summary:"A practical guide to PCOS symptoms, diagnosis, long-term management and when specialist support is important.",date:"July 2026",image:"",nutshell:"PCOS is a long-term hormonal and metabolic condition. Symptoms such as irregular periods, acne, excess facial hair and difficulty conceiving can often improve significantly with personalised treatment, lifestyle changes and regular monitoring.",introduction:"Many women ask whether PCOS will ever go away completely. The honest answer is that PCOS is usually managed rather than permanently cured. However, with the right diagnosis and treatment, most women can control their symptoms, protect their long-term health and achieve their fertility goals.",sections:[
      {heading:"What exactly is PCOS?",body:"Polycystic ovary syndrome affects ovulation and hormone balance. Some women have irregular periods, increased androgen levels or polycystic-looking ovaries, but not everyone has the same combination of symptoms.",simple:"In simple terms: the ovaries and hormones are not following a predictable monthly rhythm."},
      {heading:"Why can symptoms be so different?",body:"PCOS may affect menstrual cycles, skin, hair, weight, insulin response and fertility. Genetics, sleep, stress, activity and metabolic health can influence how strongly each symptom appears.",simple:"Two women with PCOS may need completely different treatment plans."},
      {heading:"What treatment can achieve",body:"Treatment may regulate periods, reduce acne or unwanted hair, improve insulin sensitivity and support ovulation. The plan may include nutrition and activity changes, medicines, cycle regulation or fertility treatment when appropriate.",simple:"The goal is not merely a normal scan—it is better symptoms and better long-term health."},
      {heading:"Does weight gain always mean PCOS?",body:"No. Weight changes can have several causes. Thyroid problems, medicines, sleep disturbance and other hormonal or lifestyle factors may contribute, so appropriate testing matters before blaming PCOS alone.",simple:"Correct diagnosis comes before treatment."},
      {heading:"Can women with PCOS become pregnant?",body:"Yes. Many women with PCOS conceive naturally, while others benefit from cycle tracking, ovulation treatment or fertility support. Early assessment is useful when cycles are very irregular or pregnancy is taking longer than expected.",simple:"PCOS can delay ovulation, but it does not automatically mean infertility."},
    ],faqs:[
      {q:"Will PCOS disappear after marriage or pregnancy?",a:"No. Marriage does not treat PCOS, and pregnancy does not guarantee it will disappear. Symptoms may change over time and still require follow-up."},
      {q:"Do I need medicine throughout my life?",a:"Not necessarily. Treatment changes according to symptoms, age, health risks and pregnancy plans. Some women need intermittent treatment and monitoring rather than continuous medicine."},
      {q:"Should everyone with PCOS lose weight?",a:"No. PCOS also affects women with a healthy or low body weight. Lifestyle advice and treatment must be individualised."},
      {q:"When should I consult a gynaecologist?",a:"Seek advice for very irregular or absent periods, persistent acne or excess hair, pelvic symptoms, difficulty conceiving or concerns about diabetes and long-term health."},
    ],whenToSeek:"Book a consultation if periods are repeatedly delayed or absent, symptoms are worsening, you are planning pregnancy, or online advice and self-treatment have not helped.",clinicCta:"At Shiva Krupa Polyclinic, Dr Aishwarya evaluates menstrual patterns, symptoms, metabolic health, thyroid status and fertility goals before creating a personalised PCOS plan.",takeaway:"PCOS may not have a one-time cure, but it can usually be controlled very effectively with the right diagnosis, consistent care and a treatment plan built around you."},
    {slug:"fertility-evaluation",category:"Fertility",title:"When Should You Consider a Fertility Evaluation?",heroShort:"Knowing when to seek advice can reduce uncertainty and help identify simple, treatable factors early.",summary:"A calm guide to timelines, common tests and what to expect during your first visit.",date:"July 2026",image:"",nutshell:"Most couples under 35 can seek advice after twelve months of trying; consult after six months when the woman is 35 or older, and earlier when cycles are irregular or a known condition exists.",introduction:"A fertility evaluation is not an automatic path to IVF. It is a structured review of both partners so that the next step is based on evidence rather than guesswork.",sections:[
      {heading:"When is the right time to seek advice?",body:"Couples may seek advice after twelve months of regular unprotected intercourse when the woman is under 35, or after six months when she is 35 or older. Earlier review is appropriate when periods are irregular, pelvic pain is persistent, surgery or cancer treatment has occurred, or either partner has a known fertility concern.",simple:"The right time depends on age, cycle pattern, health history and how long you have been trying."},
      {heading:"Why should both partners be evaluated?",body:"Fertility depends on factors affecting either or both partners. Assessing both at the beginning avoids months of unnecessary treatment and creates a more complete plan.",simple:"A fertility evaluation is a couple’s assessment—not only a woman’s test."},
      {heading:"What may be checked in the female partner?",body:"Depending on the history, assessment may include menstrual and ovulation review, ultrasound, ovarian reserve testing and evaluation of the uterus or fallopian tubes. Tests are selected because they can change management, not simply ordered as a standard package.",simple:"Not every patient needs every fertility test."},
      {heading:"What does the male evaluation involve?",body:"Semen analysis is usually the starting point. If a result is abnormal, it may need to be repeated under correct collection conditions before targeted hormonal, genetic or specialist evaluation is considered.",simple:"One abnormal semen report is important, but it is not always the final conclusion."},
      {heading:"Does evaluation always lead to IVF?",body:"No. The outcome may be reassurance, cycle guidance, treatment of an underlying condition, ovulation support, IUI, surgery in selected cases or IVF when clinically appropriate.",simple:"The purpose of evaluation is to choose the simplest effective next step."},
    ],faqs:[
      {q:"Can we bring previous reports?",a:"Yes. Bring prior scans, blood tests, semen analyses, treatment records and medicine lists. They can prevent unnecessary repetition and help the doctor understand the full timeline."},
      {q:"Can fertility tests be completed in one visit?",a:"The first consultation can organise the plan, but some tests depend on menstrual-cycle timing and may be completed over several days or one cycle."},
      {q:"Should we stop trying naturally during evaluation?",a:"Usually not unless your doctor advises otherwise for a specific procedure or medical reason. The consultation can clarify timing and any precautions."},
      {q:"Does irregular menstruation require earlier assessment?",a:"Yes. Very irregular or absent periods may indicate inconsistent ovulation and are a reason to seek advice earlier rather than waiting a full year."},
    ],whenToSeek:"Consult earlier for irregular periods, severe pelvic pain, previous pelvic surgery, recurrent pregnancy loss or known male-factor concerns.",clinicCta:"Dr Aishwarya offers clear fertility assessment and discusses simpler options before advanced treatment is considered.",takeaway:"Early clarity can save time, reduce anxiety and lead to the most appropriate next step."},
    {slug:"first-trimester",category:"Pregnancy",title:"Your First Trimester: What Is Normal and When Should You Call the Doctor?",heroShort:"Early pregnancy brings rapid changes. Understanding common symptoms and warning signs helps you feel more confident.",summary:"Common symptoms, important check-ups and warning signs that should never be ignored.",date:"June 2026",image:"",nutshell:"Nausea, tiredness and mild cramps can be common, but heavy bleeding, severe pain, fainting or persistent vomiting need prompt medical advice.",introduction:"The first twelve weeks are exciting and often worrying. A planned early consultation helps confirm the pregnancy, review medicines and organise the right scans and tests.",sections:[
      {heading:"Which early-pregnancy symptoms are common?",body:"Breast tenderness, tiredness, nausea, food aversions, frequent urination, bloating and mild intermittent cramps can occur as hormones change. Symptoms vary considerably and may also fluctuate from day to day.",simple:"Having fewer symptoms does not automatically mean that something is wrong."},
      {heading:"When should the first appointment happen?",body:"Contact the clinic after a positive test so timing can be planned from the last menstrual period, symptoms and medical history. Earlier assessment may be needed after fertility treatment, previous ectopic pregnancy, recurrent loss, pain or bleeding.",simple:"The first appointment is timed to answer a clinical question—not simply as early as possible."},
      {heading:"What happens during an early scan?",body:"An early ultrasound may confirm that the pregnancy is located inside the uterus, estimate gestational age, assess viability when timing permits and check for more than one pregnancy. A scan performed too early may need to be repeated.",simple:"An inconclusive very-early scan does not always indicate a problem."},
      {heading:"Which medicines and supplements matter?",body:"Folic acid is commonly recommended, while the dose depends on individual risk. All prescription medicines, over-the-counter products and supplements should be reviewed; do not abruptly stop essential treatment without medical advice.",simple:"Natural or herbal products are not automatically safe during pregnancy."},
      {heading:"Which warning signs need urgent attention?",body:"Heavy bleeding, severe or one-sided abdominal pain, shoulder-tip pain, fainting, high fever, breathing difficulty or persistent vomiting with dehydration require prompt medical assessment.",simple:"When symptoms are severe or rapidly worsening, seek help rather than waiting for the next routine visit."},
    ],faqs:[
      {q:"Is mild spotting always a miscarriage?",a:"No. Light spotting can have several causes, but any bleeding in pregnancy should be discussed so the amount, pain, gestational age and risk factors can be assessed."},
      {q:"Can I exercise in the first trimester?",a:"Many women can continue appropriate activity, but intensity and restrictions depend on previous fitness, symptoms and pregnancy-related risks. Ask for individual advice."},
      {q:"What can help with nausea?",a:"Small frequent meals, adequate fluids and avoiding triggers may help. Persistent vomiting, weight loss, reduced urination or inability to keep fluids down needs medical treatment."},
      {q:"When can a heartbeat be seen?",a:"It depends on gestational age, ovulation timing and scan method. If a scan is performed very early, repeating it after an appropriate interval may be more informative."},
    ],whenToSeek:"Seek urgent advice for heavy bleeding, severe one-sided pain, fainting, fever or inability to keep fluids down.",clinicCta:"Dr Aishwarya provides early pregnancy assessment, antenatal planning and clear guidance for each stage.",takeaway:"Most early symptoms are manageable, but knowing the warning signs ensures you receive help at the right time."},
    {slug:"male-infertility-causes-treatment",category:"Fertility",title:"Male Infertility: Causes, Symptoms, Diagnosis and Treatment",heroShort:"Male-factor fertility concerns are common and often manageable. A structured evaluation helps couples avoid delay, guesswork and unnecessary treatment.",summary:"Understand common causes, the role of semen analysis and how timely evaluation can improve the chances of conception.",date:"July 2026",image:"",nutshell:"Male factors contribute to fertility difficulty in a significant number of couples. Evaluation usually begins with medical history and semen analysis, followed by focused tests only when indicated.",introduction:"Fertility is a shared concern, not solely a woman’s responsibility. Evaluating both partners early can identify treatable factors and help the couple choose the most appropriate next step.",sections:[
      {heading:"What can affect male fertility?",body:"Sperm production and function may be affected by varicocele, infection, hormonal conditions, genetic factors, some medicines, heat exposure, smoking, alcohol, obesity or previous surgery. Sometimes no single cause is found.",simple:"A fertility concern does not automatically mean permanent infertility."},
      {heading:"Why is semen analysis important?",body:"Semen analysis evaluates sperm concentration, movement and shape. Since results can vary, an abnormal test may need to be repeated under the correct collection conditions before conclusions are made.",simple:"One report should be interpreted in context—not viewed as a final verdict."},
      {heading:"What treatment options are available?",body:"Treatment depends on the cause and may include lifestyle changes, treatment of infection or hormonal problems, specialist review, surgery in selected cases or assisted reproduction such as IUI, IVF or ICSI.",simple:"The right treatment is based on the cause, not a standard fertility package."},
    ],faqs:[
      {q:"Should both partners be evaluated at the same time?",a:"Yes. Parallel evaluation avoids unnecessary delay and gives a clearer picture of the couple’s combined fertility factors."},
      {q:"Can stress alone cause male infertility?",a:"Stress can affect sexual function and lifestyle, but persistent abnormal semen results should not be attributed to stress without proper evaluation."},
      {q:"Can semen parameters improve?",a:"They may improve when a treatable factor is identified, although sperm production takes several weeks and changes are not immediate."},
    ],whenToSeek:"Consider evaluation after twelve months of trying, after six months when the female partner is 35 or older, or earlier with testicular problems, sexual difficulties, previous surgery, cancer treatment or known medical conditions.",clinicCta:"At Shiva Krupa Polyclinic, fertility evaluation considers both partners and focuses on clinically useful tests before discussing treatment options.",takeaway:"Male fertility concerns are common, and early evaluation can replace uncertainty with a clear, evidence-based plan."},
  ],
  videos:[
    {category:"Dr Aishwarya · Fertility treatment",title:"How doctors choose between IUI, IVF and ICSI",summary:"Dr Aishwarya explains why the choice is based on the couple’s medical findings rather than a standard treatment package.",url:"https://www.instagram.com/dr.aishwarya02/reel/DVv0qPhEuQ6/",image:"/media/iui-ivf.webp"},
    {category:"Dr Aishwarya · Pregnancy planning",title:"Weight management while planning pregnancy",summary:"Dr Aishwarya discusses why healthy weight and metabolic health matter before conception.",url:"https://www.instagram.com/reel/DSRaKyRCL9F/",image:"/media/pregnancy-planning.webp"},
    {category:"Dr Aishwarya · Fertility awareness",title:"Infertility is a health conversation",summary:"Dr Aishwarya encourages couples to seek evidence-led guidance without shame or silence.",url:"https://www.instagram.com/reel/DbLA_hVixdD/",image:"/media/fertility-awareness.webp"},
  ],
  instagramVideoVersion:3,
  galleryImages:[
    {title:"Clinic reception",category:"Clinic",image:""},
    {title:"Consultation space",category:"Clinic",image:""},
    {title:"Patient education",category:"Care",image:""},
  ],
  testimonials:[
    {name:"Laxmi & Sachin",quote:"Her treatment and advice gave us tremendous support through pregnancy. We are grateful for her care and guidance.",source:"Practo · Verified",rating:5},
    {name:"Archana Bharath",quote:"After four years of trying to conceive and meeting several doctors, I met Dr Aishwarya, conceived through IVF and later delivered a baby boy.",source:"Practo · Verified",rating:5},
    {name:"Vidya",quote:"She listens carefully and explains the best solutions in a detailed yet simple manner. She guided me through a crucial time in my life.",source:"Practo · Verified",rating:5},
    {name:"Satish & Girija",quote:"Her friendly approach, timely decisions and commitment through pregnancy helped fulfil our dream of parenthood.",source:"Practo · Verified",rating:5},
    {name:"Verified Patient",quote:"She provided a clear solution quickly and was friendly, calm and helpful throughout the consultation.",source:"Practo · Recommended",rating:5},
    {name:"Swathi S Prakash",quote:"Recommended Dr Aishwarya after consulting her for a gynaecological concern.",source:"Practo · Verified",rating:5},
  ],
  verifiedReviewsVersion:1,
};

export type SiteSettings = typeof defaultSettings;
